name: Build Astral Quest

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  nds:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Put sync-none.specs where the toolchain will look for specs files.
      - name: Install sync-none.specs (no GCC needed)
        shell: bash
        run: |
          set -euo pipefail
          # Prefer the canonical arm-none-eabi lib folder; create if missing.
          DS_DIR="/opt/devkitpro/devkitARM/arm-none-eabi/lib"
          install -d "$DS_DIR"
          printf '%s\n' \
            '%rename link sync_sync_link' \
            '*link:' \
            '--defsym=__sync_synchronize=__sync_synchronize_none %(sync_sync_link)' \
            > "$DS_DIR/sync-none.specs"
          echo "sync-none.specs installed at: $DS_DIR"
          ls -l "$DS_DIR/sync-none.specs" || true

          # Belt & braces: also copy into versioned GCC lib dirs if they exist.
          if ls /opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/* >/dev/null 2>&1; then
            for d in /opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/*; do
              cp "$DS_DIR/sync-none.specs" "$d/sync-none.specs"
              echo "Also installed in: $d"
            done
          fi

      - name: Toolchain info
        shell: bash
        run: |
          set -euo pipefail
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM="$DEVKITPRO/devkitARM"
          export PATH="$DEVKITARM/bin:$PATH"
          echo "DEVKITPRO=$DEVKITPRO"
          echo "DEVKITARM=$DEVKITARM"
          command -v arm-none-eabi-gcc || (echo "arm-none-eabi-gcc missing from PATH" && exit 1)
          arm-none-eabi-gcc --version

      - name: Build
        shell: bash
        run: |
          set -euo pipefail
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM="$DEVKITPRO/devkitARM"
          export PATH="$DEVKITARM/bin:$PATH"
          make

      - name: Upload ROM + debug
        uses: actions/upload-artifact@v4
        with:
          name: astral_quest_build
          path: |
            astral_quest.nds
            astral_quest.elf
            astral_quest.map
          if-no-files-found: error
