name: Build Astral Quest

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  nds:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Put sync-none.specs in the exact folder that holds ds_arm9.specs
      - name: Install sync-none.specs next to ds_arm9.specs
        shell: bash
        run: |
          set -euo pipefail
          DS_SPECS="$(arm-none-eabi-gcc -print-file-name=ds_arm9.specs)"
          DS_DIR="$(dirname "$DS_SPECS")"
          echo "ds_arm9.specs: $DS_SPECS"
          echo "Installing sync-none.specs into: $DS_DIR"
          install -d "$DS_DIR"
          printf '%s\n' \
            '%rename link sync_sync_link' \
            '*link:' \
            '--defsym=__sync_synchronize=__sync_synchronize_none %(sync_sync_link)' \
            > "$DS_DIR/sync-none.specs"
          ls -l "$DS_DIR/sync-none.specs"

      - name: Build
        run: make

      - name: Upload ROM + debug
        uses: actions/upload-artifact@v4
        with:
          name: astral_quest_build
          path: |
            astral_quest.nds
            astral_quest.elf
            astral_quest.map
          if-no-files-found: error
