name: Build Astral Quest

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  nds:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Make the toolchain visible to subsequent steps
      - name: Prepare toolchain env
        shell: bash
        run: |
          set -euo pipefail
          echo "DEVKITPRO=/opt/devkitpro" >> "$GITHUB_ENV"
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> "$GITHUB_ENV"
          echo "/opt/devkitpro/devkitARM/bin" >> "$GITHUB_PATH"

      # ds_arm9.specs includes 'sync-none.specs' which is missing in this container.
      # Install the shim right next to ds_arm9.specs so the include resolves.
      - name: Install sync-none.specs beside ds_arm9.specs
        shell: bash
        run: |
          set -euo pipefail
          DS_SPECS="$(arm-none-eabi-gcc -print-file-name=ds_arm9.specs)"
          DS_DIR="$(dirname "$DS_SPECS")"
          install -d "$DS_DIR"
          printf '%s\n' \
            '%rename link sync_sync_link' \
            '*link:' \
            '--defsym=__sync_synchronize=__sync_synchronize_none %(sync_sync_link)' \
            > "$DS_DIR/sync-none.specs"
          echo "Installed: $DS_DIR/sync-none.specs"

      - name: Build
        shell: bash
        run: |
          set -euo pipefail
          make -j2
          ls -l astral_quest.* || true
          ls -l build || true

      - name: Upload ROM + debug
        uses: actions/upload-artifact@v4
        with:
          name: astral_quest_build
          path: |
            astral_quest.nds
            astral_quest.elf
            astral_quest.map
            build/astral_quest.map
          if-no-files-found: error
