name: Build Astral Quest

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  nds:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Workaround: ds_arm9.specs includes sync-none.specs which is missing in the container.
      - name: Install sync-none.specs shim
        shell: bash
        run: |
          set -euo pipefail

          install -d /opt/devkitpro/devkitARM/arm-none-eabi/lib

          cat > /opt/devkitpro/devkitARM/arm-none-eabi/lib/sync-none.specs <<'EOF'
          %rename link sync_sync_link
          *link:
          --defsym=__sync_synchronize=__sync_synchronize_none %(sync_sync_link)
          EOF

          if ls /opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/* >/dev/null 2>&1; then
            for d in /opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/*; do
              cp /opt/devkitpro/devkitARM/arm-none-eabi/lib/sync-none.specs "$d/sync-none.specs"
            done
          fi

      - name: Build
        run: make

      - name: Upload ROM + debug
        uses: actions/upload-artifact@v4
        with:
          name: astral_quest_build
          path: |
            astral_quest.nds
            astral_quest.elf
            astral_quest.map
          if-no-files-found: error
